sudo: false
language: python
notifications:
  email:
    recipients:
      - 523131316@qq.com
    on_success: always # default: change
    on_failure: always # default: always
python:
  - "3.8"
  - "3.7"
  - "3.6"
before_install:
  - pip install -r requirements.txt
script:
  - python setup.py install
  - python test.py
after_success:
  cd .
